{
 "title": "☕ spring-demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Commandes / min",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(orders_placed_total{outcome=\"success\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Commandes refusées / min",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(orders_placed_total{outcome=\"rejected\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Pods Ready (order)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\".*-order\"})"
    }
   ]
  },
  {
   "title": "Taux d'erreur 5xx",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[2m])) / sum(rate(http_server_requests_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "Requêtes / s par service et statut",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (application, status) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{application}} {{status}}"
    }
   ]
  },
  {
   "title": "Latence p95",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, application) (rate(http_server_requests_seconds_bucket[2m])))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Heap JVM utilisée",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 13, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU par Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 13, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\".*-(catalog|order)-.*\", container!=\"\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}