apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "demo"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
