{{- /* Module 109 : Prometheus Operator scrape /actuator/prometheus des deux services */ -}}
{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-spring-demo
  labels:
    {{- include "spring-demo.labels" (dict "root" . "name" "spring-demo") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: spring-demo
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
